name: Joli Backend CI/CD

on:
  push:
    branches:
      - develop

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test


  deploy:
    name: Deploy Cloud Run
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Login Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy joli-dev \
          --source . \
          --region northamerica-south1 \
          --platform managed \
          --allow-unauthenticated