name: Joli Backend CI/CD

on:
  push:
    branches:
      - develop

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test


  